pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f tomcat-java-project/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Storing the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            steps {
                sh "pwd"
                sh "ls -a"
                sh "docker build ./dockerized-java-tomcat-project -t tomcatsamplewebapp:${env.BUILD_ID}"
            }
        }

    }
}
